<a href="https://colab.research.google.com/github/Saifullah785/Predictive_Maintenance_ML_Projects/blob/main/Project_05_Predictive%20Maintenance_Milling_Machine/Project_05_Predictive_Maintenance_Milling_Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Explore**

In [ ]:
import numpy as np
import pandas as pd

from IPython.core.display import display, HTML
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio


import seaborn as sns
from importlib import reload
import matplotlib.pyplot as plt
import matplotlib
import warnings

# Configure Jupyter Notebook
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)
pd.set_option('display.expand_frame_repr', False)

# pd.set_option('max_colwidth', -1)
display(HTML("<style>div.output_scroll { height: 35em; }</style>"))

reload(plt)
%matplotlib inline
%config InlineBackend.figure_format ='retina'

warnings.filterwarnings('ignore')

# configure plotly graph objects
pio.renderers.default = 'iframe'

# pio.renderers.default = 'vscode'

pio.templates["ck_template"] = go.layout.Template(
    layout_colorway = px.colors.sequential.Viridis,
#     layout_hovermode = 'closest',
#     layout_hoverdistance = -1,
    layout_autosize=False,
    layout_width=800,
    layout_height=600,
    layout_font = dict(family="Calibri Light"),
    layout_title_font = dict(family="Calibri"),
    layout_hoverlabel_font = dict(family="Calibri Light"),
#     plot_bgcolor="white",
)
# pio.templates.default = 'seaborn+ck_template+gridon'
pio.templates.default = 'ck_template+gridon'
# pio.templates.default = 'seaborn+gridon'
# pio.templates

In [ ]:
df = pd.read_csv('/content/ai4i2020.csv')
# df = pd.read_csv('ai4i2020.csv')

In [ ]:
df.head()

   UDI Product ID Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF
0    1     M14860    M                298.1                    308.6                    1551         42.8                0                0    0    0    0    0    0
1    2     L47181    L                298.2                    308.7                    1408         46.3                3                0    0    0    0    0    0
2    3     L47182    L                298.1                    308.5                    1498         49.4                5                0    0    0    0    0    0
3    4     L47183    L                298.2                    308.6                    1433         39.5                7                0    0    0    0    0    0
4    5     L47184    L                298.2                    308.7                    1408         40.0                9                0    0    0    0    0    0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

In [ ]:
df.describe(include='all').T

                           count unique     top  freq       mean         std     min      25%     50%      75%      max
UDI                      10000.0    NaN     NaN   NaN     5000.5  2886.89568     1.0  2500.75  5000.5  7500.25  10000.0
Product ID                 10000  10000  L57163     1        NaN         NaN     NaN      NaN     NaN      NaN      NaN
Type                       10000      3       L  6000        NaN         NaN     NaN      NaN     NaN      NaN      NaN
Air temperature [K]      10000.0    NaN     NaN   NaN  300.00493    2.000259   295.3    298.3   300.1    301.5    304.5
Process temperature [K]  10000.0    NaN     NaN   NaN  310.00556    1.483734   305.7    308.8   310.1    311.1    313.8
Rotational speed [rpm]   10000.0    NaN     NaN   NaN  1538.7761  179.284096  1168.0   1423.0  1503.0   1612.0   2886.0
Torque [Nm]              10000.0    NaN     NaN   NaN   39.98691    9.968934     3.8     33.2    40.1     46.8     76.6
Tool wear [min]          10000.0    NaN     NaN   NaN    107.951   63.654147     0.0     53.0   108.0    162.0    253.0
Machine failure          10000.0    NaN     NaN   NaN     0.0339    0.180981     0.0      0.0     0.0      0.0      1.0
TWF                      10000.0    NaN     NaN   NaN     0.0046    0.067671     0.0      0.0     0.0      0.0      1.0
HDF                      10000.0    NaN     NaN   NaN     0.0115    0.106625     0.0      0.0     0.0      0.0      1.0
PWF                      10000.0    NaN     NaN   NaN     0.0095    0.097009     0.0      0.0     0.0      0.0      1.0
OSF                      10000.0    NaN     NaN   NaN     0.0098    0.098514     0.0      0.0     0.0      0.0      1.0
RNF                      10000.0    NaN     NaN   NaN     0.0019     0.04355     0.0      0.0     0.0      0.0      1.0

In [ ]:
df.replace("?",np.nan,inplace=True)

In [ ]:
for column in df.columns:
    try:
        df[column]=df[column].astype(float)
    except:
        pass

In [ ]:
# show the numeric characters
df_numeric = df.select_dtypes(include=[np.number])
df_numeric.describe(include='all').T

In [ ]:
plt.figure(figsize=(15,15))
plot_kws={"s": 1}
sns.heatmap(df.isna().transpose(),
            cmap='cividis',
            linewidths=0.0,
           ).set_facecolor('white')

In [ ]:
plt.figure(figsize=(10,10))
threshold = 0.80
sns.set_style("whitegrid", {"axes.facecolor": ".0"})
df_cluster2 = df.corr()
mask = df_cluster2.where((abs(df_cluster2) >= threshold)).isna()
plot_kws={"s": 1}
sns.heatmap(df_cluster2,
            cmap='RdYlBu',
            annot=True,
            mask=mask,
            linewidths=0.2,
            linecolor='lightgrey').set_facecolor('white')

In [ ]:
from pandas_profiling import ProfileReport

In [ ]:
%%time
profile = ProfileReport(df,
                        title="Predictive Maintenance",
                        dataset={"description": "This profiling report was generated for Carl Kirstein",
                                 "copyright_holder": "Carl Kirstein",
                                 "copyright_year": "2022",
                                },
                        explorative=True,
                       )
profile

In [ ]:
df.drop(['UDI','Product ID'],axis=1,inplace=True)

In [ ]:
df.drop(['TWF','HDF','PWF','OSF','RNF'],axis=1,inplace=True)

In [ ]:
df.drop(['Type'],axis=1,inplace=True)

In [ ]:
list(df)

In [ ]:
df = pd.get_dummies(df,drop_first=True)

In [ ]:
features = list(df.columns)

In [ ]:
for feature in features:
    print(feature + " - " + str(len(df[df[feature].isna()])))