<a href="https://colab.research.google.com/github/Saifullah785/Predictive_Maintenance_ML_Projects/blob/main/Project_01_Predictive_Maintenance_Using_Machine_Learning/Project_01_Predictive_Maintenance_Using_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.metrics import accuracy_score, classification_report, recall_score, precision_score, f1_score
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.pipeline import Pipeline
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Define the column names
column_names = ['Temperature', 'Vibration', 'Pressure', 'Humidity', 'RPM', 'Voltage', 'Current', 'Sound_Level', 'Oil_Quality', 'Load','Machine Type','Failure Type','Component Type']

# Generate random data for each column
num_rows = 100
data = {
    'Temperature': np.random.uniform(20, 100, num_rows),  # Temperature between 20 and 100
    'Vibration': np.random.uniform(0, 1, num_rows),  # Vibration between 0 and 1
    'Pressure': np.random.uniform(1, 10, num_rows),  # Pressure between 1 and 10
    'Humidity': np.random.uniform(30, 80, num_rows),  # Humidity between 30 and 80
    'RPM': np.random.uniform(1000, 5000, num_rows),  # RPM between 1000 and 5000
    'Voltage': np.random.uniform(110, 240, num_rows),  # Voltage between 110 and 240
    'Current': np.random.uniform(1, 10, num_rows),  # Current between 1 and 10
    'Sound_Level': np.random.uniform(60, 100, num_rows),  # Sound level between 60 and 100
    'Oil_Quality': np.random.uniform(0, 1, num_rows),  # Oil quality between 0 and 1
    'Load': np.random.uniform(0, 100, num_rows),  # Load between 0 and 100
    'Machine Type': np.random.choice(['Pump', 'Motor', 'Compressor', 'Turbine'], num_rows),  # Randomly assigns one of the four machine types to each row
    'Failure Type': np.random.choice(['Overheating', 'Vibration, Wear', 'Electrical', 'No Failure'], num_rows),  # Randomly assigns one of the four failure types to each row
    'Component Type': np.random.choice(['Bearing', 'Gear', 'Seal', 'Fan Blade'], num_rows)  # Randomly assigns one of the four component types to each row
}

# Combine columns to the data to create the dataset
pred = pd.DataFrame(data, columns=column_names)

In [3]:
pred.head()

,Temperature,Vibration,Pressure,Humidity,RPM,Voltage,Current,Sound_Level,Oil_Quality,Load,Machine Type,Failure Type,Component Type
0,20.854223,0.712101,9.101596,42.627322,2110.333538,238.999576,5.003808,70.316703,0.223225,99.106986,Motor,Overheating,Fan Blade
1,29.906981,0.821418,3.171454,60.943651,2581.206364,158.497938,4.059165,80.406056,0.964889,1.322545,Motor,"Vibration, Wear",Fan Blade
2,57.166809,0.174699,1.388215,69.375544,3099.447651,174.234351,3.574903,97.632284,0.710243,0.524365,Pump,No Failure,Gear
3,60.440601,0.555170,5.801846,48.976326,2742.650298,160.818942,9.014362,82.455376,0.788856,7.117324,Motor,Electrical,Gear
4,26.637819,0.698308,9.071902,76.689041,3275.899170,222.361544,6.694988,93.557420,0.909482,54.765293,Pump,Overheating,Fan Blade

In [4]:
pred.tail()

,Temperature,Vibration,Pressure,Humidity,RPM,Voltage,Current,Sound_Level,Oil_Quality,Load,Machine Type,Failure Type,Component Type
95,34.383678,0.029681,8.591269,34.863910,1086.007002,184.652332,8.838653,90.965512,0.302823,40.490602,Compressor,"Vibration, Wear",Bearing
96,93.881623,0.826703,2.479063,62.070825,4757.832603,135.724958,2.345499,88.073332,0.873333,90.059005,Turbine,No Failure,Fan Blade
97,22.931420,0.490033,2.307850,76.601222,3637.246533,120.081222,2.047014,86.941141,0.518003,27.528300,Pump,Overheating,Seal
98,77.763180,0.603955,1.526870,49.363374,2125.131591,138.768696,1.917140,93.557783,0.582240,97.561843,Turbine,No Failure,Bearing
99,93.846281,0.363620,2.027627,42.133658,4302.861892,148.995050,6.421180,93.432205,0.973540,25.204979,Compressor,Overheating,Bearing

# **Exploratory Data Analysis**

In [5]:
pred.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Temperature     100 non-null    float64
 1   Vibration       100 non-null    float64
 2   Pressure        100 non-null    float64
 3   Humidity        100 non-null    float64
 4   RPM             100 non-null    float64
 5   Voltage         100 non-null    float64
 6   Current         100 non-null    float64
 7   Sound_Level     100 non-null    float64
 8   Oil_Quality     100 non-null    float64
 9   Load            100 non-null    float64
 10  Machine Type    100 non-null    object
 11  Failure Type    100 non-null    object
 12  Component Type  100 non-null    object
dtypes: float64(10), object(3)
memory usage: 10.3+ KB